//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.BusinessEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gemEntities1 : DbContext
    {
        public gemEntities1()
            : base("name=gemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<fluency_level> fluency_level { get; set; }
        public DbSet<journey> journeys { get; set; }
        public DbSet<journey_practice> journey_practice { get; set; }
        public DbSet<measure> measures { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<mission> missions { get; set; }
        public DbSet<mission_member_measure_assesment> mission_member_measure_assesment { get; set; }
        public DbSet<mission_practice> mission_practice { get; set; }
        public DbSet<practice> practices { get; set; }
        public DbSet<team> teams { get; set; }
        public DbSet<team_focus> team_focus { get; set; }
        public DbSet<team_journey> team_journey { get; set; }
        public DbSet<team_journey_member> team_journey_member { get; set; }
        public DbSet<team_journey_member_role> team_journey_member_role { get; set; }
        public DbSet<team_journey_practice> team_journey_practice { get; set; }
    }
}
