//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class journey_practice
    {
        public int JourneyPracticeId { get; set; }
        public Nullable<int> JourneyId { get; set; }
        public Nullable<int> PracticeId { get; set; }
    
        public virtual journey journey { get; set; }
        public virtual practice practice { get; set; }
    }
}
