//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class measure
    {
        public measure()
        {
            this.mission_member_measure_assesment = new HashSet<mission_member_measure_assesment>();
        }
    
        public int MeasureId { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public string Measure1 { get; set; }
        public string Description { get; set; }
        public string Why { get; set; }
        public string When { get; set; }
    
        public virtual ICollection<mission_member_measure_assesment> mission_member_measure_assesment { get; set; }
        public virtual practice practice { get; set; }
    }
}
