//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_mission_practice
    {
        public int MemberMissionPracticeId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> MissionPracticeId { get; set; }
        public string RejectForReason { get; set; }
        public Nullable<sbyte> Status { get; set; }
    
        public virtual member member { get; set; }
        public virtual mission_practice mission_practice { get; set; }
    }
}
