//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mission_practice
    {
        public int MissionPracticeId { get; set; }
        public int MissionId { get; set; }
        public int PracticeId { get; set; }
    
        public virtual mission mission { get; set; }
        public virtual practice practice { get; set; }
    }
}
