//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mission
    {
        public mission()
        {
            this.mission_member_measure_assesment = new HashSet<mission_member_measure_assesment>();
            this.mission_practice = new HashSet<mission_practice>();
        }
    
        public int MissionId { get; set; }
        public int TeamJourneyId { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> Score { get; set; }
    
        public virtual ICollection<mission_member_measure_assesment> mission_member_measure_assesment { get; set; }
        public virtual ICollection<mission_practice> mission_practice { get; set; }
        public virtual team_journey team_journey { get; set; }
    }
}
