//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class practice
    {
        public practice()
        {
            this.journey_practice = new HashSet<journey_practice>();
            this.measures = new HashSet<measure>();
            this.mission_practice = new HashSet<mission_practice>();
            this.team_journey_practice = new HashSet<team_journey_practice>();
        }
    
        public int PracticeId { get; set; }
        public Nullable<int> FluencyLevelId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SequenceNum { get; set; }
        public Nullable<int> PrerequisiteNum { get; set; }
    
        public virtual fluency_level fluency_level { get; set; }
        public virtual ICollection<journey_practice> journey_practice { get; set; }
        public virtual ICollection<measure> measures { get; set; }
        public virtual ICollection<mission_practice> mission_practice { get; set; }
        public virtual ICollection<team_journey_practice> team_journey_practice { get; set; }
    }
}
