//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gem.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_focus
    {
        public team_focus()
        {
            this.journeys = new HashSet<journey>();
        }
    
        public int TeamFocusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<journey> journeys { get; set; }
    }
}
